### ISSUE TITLE
Where is DevCartel MT5 gateway?

### ISSUE THREAD

**Issue by ahangarha** [devcartel/pymt5#3]
Hi

This project is dependent on DevCartel MT5 gateway. I tried the link to the github repo, but I faced with 404 error. The repository of this project is removed totally.

May you please inform me how to get access to this project to be able to use PyMT5

**Comment by wiwat-tharateeraparb** [comment]
Hi, the MT5 Gateway software is on a private repo. It is available through our http://devcartel.com/devcartelgateway64. Once you are a subscriber, we will grant your GitHub username access and you can download the gateway to install on your MT5 server. The private repo also has document as well. Thanks.

**Comment by ahangarha** [comment]
I didnt get info on how to subscribe. Isn't it a free/opensource software?

**Comment by wiwat-tharateeraparb** [comment]
At the moment, our DevCartelGateway64 for MT5 is not a freeware.

**Comment by ahangarha** [comment]
I didnt ask if it is freeware. I asked about free (libre / open source)
software.

Moreover, I didnt find a way to subscribe.

I think it is going off topic here to talk about this. Pleaae provide more
info on your website about this issue

**Comment by wiwat-tharateeraparb** [comment]
We have made a decision to turn https://github.com/devcartel/devcartelgateway64 public. You can download the software there. If you feel like getting support from us, please visit http://devcartel.com/devcartelgateway64 for details or this [link](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=CKHUBNTFNDCB8) to set up a payment. Many thanks.

**Comment by ahangarha** [comment]
Awesome
