### ISSUE TITLE
Where are the sources for DevCartelGateway64?

### ISSUE THREAD

**Issue by eabase** [devcartel/pymt5#5]
You said in [here]() that:

> We have made a decision to turn https://github.com/devcartel/devcartelgateway64 public. You can download the software there. If you feel like getting support from us, please visit http://devcartel.com/devcartelgateway64 for details or this [link](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=CKHUBNTFNDCB8) to set up a payment. Many thanks.

But I can't find any sources to that exe. Where are they?

**Comment by wiwat-tharateeraparb** [comment]
Binary releases are in our GitHub repo https://github.com/devcartel/devcartelgateway64/releases

**Comment by eabase** [comment]
@wiwat-tharateeraparb 
Ok, so since you repeat the obvious it is not open source, nor MIT Licensed, am I correct?
So please either remove the MIT license or provide the source code.

**Comment by wiwat-tharateeraparb** [comment]
@eabase DevCartelGateway64 is not open source.

**Comment by eabase** [comment]
Great Wiwat,
But then please change the license, because [MIT is Open Source](https://fossbytes.com/open-sources-license-type/).

> MIT LICENSE

It’s the shortest and perhaps most used of all the popular open source licenses. Its terms are loose and more open than most others. The main giving of this license is:

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

This basically means that you can use, copy, and modify the software however you want. No one can prevent you from using it in any other project. You can give the software under it for free, or sell it. No restrictions on distribution howsoever. Anyone can do whatever one fancies with the code licensed under MIT license, as long as it’s accompanied by the license.
